### ISSUE TITLE
Replace

### ISSUE THREAD

**Issue by kzeng10** [Pomax/node-flickrapi#72]
This API has the upload function, but what about replace? It's essentially the same as upload, but you'll just have to change the url from `https://up.flickr.com/services/upload/` to `https://up.flickr.com/services/replace/`

**Comment by Pomax** [comment]
essentially, but also very different: uploading is non destructive (no data is lost), whereas replacing destroys what was on Flickr, so that's going to need user permissions. I'm happy to offer a simple utility function for uploads, but for replacement you're going to have to write your own function (you can of course just copy what's in the utils.js file and adapt it for `replace`) because there is no good way to safely do those replacements without application-specific logic to ensure the user gave their permission to destroy photos already on Flickr.
